name: ''
storage_path: /opt/walrus/db
blocklist_path: null
db_config:
  global:
    max_open_files: 512000
  standard:
    enable_blob_files: false
    min_blob_size: 0
    blob_file_size: 0
    blob_compression_type: none
    enable_blob_garbage_collection: false
    blob_garbage_collection_age_cutoff: 0.0
    blob_garbage_collection_force_threshold: 0.0
    blob_compaction_read_ahead_size: 0
    write_buffer_size: 67108864
    target_file_size_base: 67108864
    max_bytes_for_level_base: 536870912
    block_cache_size: 67108864
    pin_l0_filter_and_index_blocks_in_block_cache: true
  optimized_for_blobs:
    enable_blob_files: true
    min_blob_size: 1048576
    blob_file_size: 268435456
    blob_compression_type: zstd
    enable_blob_garbage_collection: true
    blob_garbage_collection_age_cutoff: 0.5
    blob_garbage_collection_force_threshold: 0.5
    blob_compaction_read_ahead_size: 10485760
    write_buffer_size: 268435456
    target_file_size_base: 67108864
    max_bytes_for_level_base: 536870912
    block_cache_size: 268435456
    pin_l0_filter_and_index_blocks_in_block_cache: true
  node_status: null
  metadata: null
  blob_info:
    block_cache_size: 536870912
  per_object_blob_info:
    block_cache_size: 536870912
  event_cursor: null
  shard: null
  shard_status: null
  shard_sync_progress: null
  pending_recover_slivers: null
  certified: null
  pending: null
  attested: null
  failed_to_attest: null
  checkpoint_store: null
  walrus_package_store: null
  committee_store: null
  event_store: null
  init_state: null
protocol_key_pair:
  path: /opt/walrus/config/protocol.key
next_protocol_key_pair: null
network_key_pair:
  path: /opt/walrus/config/network.key
public_host: 0.0.0.0
public_port: 9185
metrics_address: 127.0.0.1:9184
rest_api_address: 0.0.0.0:9185
rest_server:
  http2_max_concurrent_streams: 1000
  http2_initial_stream_window_size: null
  http2_initial_connection_window_size: null
  http2_max_pending_accept_reset_streams: 100
  http2_adaptive_window: true
rest_graceful_shutdown_period_secs: 60
sui:
  rpc: https://fullnode.testnet.sui.io:443
  system_object: 0xa2637d13d171b278eadfa8a3fbe8379b5e471e1f3739092e5243da17fc8090eb
  staking_object: 0xca7cf321e47a1fc9bfd032abc31b253f5063521fd5b4c431f2cdd3fee1b4ec00
  event_polling_interval_millis: 400
  wallet_config: /opt/walrus/config/sui_config.yaml
  backoff_config:
    min_backoff_millis: 1000
    max_backoff_millis: 30000
    max_retries: 5
  gas_budget: null
  rpc_fallback_config: null
  request_timeout: null
blob_recovery:
  max_concurrent_blob_syncs: 100
  max_concurrent_sliver_syncs: 2000
  max_proof_cache_elements: 7500
  retry_interval_min_secs: 1
  retry_interval_max_secs: 3600
  metadata_request_timeout_secs: 5
  max_concurrent_metadata_requests: 1
  sliver_request_timeout_secs: 300
  invalidity_sync_timeout_secs: 300
  node_connect_timeout_secs: 1
  experimental_sliver_recovery_additional_symbols: 0
tls:
  disable_tls: false
  certificate_path: null
shard_sync_config:
  sliver_count_per_sync_request: 1000
  shard_sync_retry_min_backoff_secs: 60
  shard_sync_retry_max_backoff_secs: 600
  max_concurrent_blob_recovery_during_shard_recovery: 100
  blob_certified_check_interval_secs: 60
  max_concurrent_metadata_fetch: 100
  shard_sync_concurrency: 10
  shard_sync_retry_switch_to_recovery_interval_secs: 43200
  restart_shard_sync_always_retry_transfer_first: true
event_processor_config:
  pruning_interval_secs: 3600
  checkpoint_request_timeout_secs: 60
  adaptive_downloader_config:
    min_workers: 1
    max_workers: 10
    initial_workers: 5
    scale_up_lag_threshold: 100
    scale_down_lag_threshold: 10
    scale_cooldown_secs: 10
    base_config:
      min_retries: 10
      initial_delay_millis: 150
      max_delay_millis: 2000
    channel_config:
      work_queue_buffer_factor: 3
      result_queue_buffer_factor: 3
  event_stream_catchup_min_checkpoint_lag: 20000
use_legacy_event_provider: false
disable_event_blob_writer: false
commission_rate: 6000
voting_params:
  storage_price: 100000
  write_price: 20000
  node_capacity: 250000000000
metadata:
  image_url: ''
  project_url: ''
  description: ''
  extra_fields: []
metrics_push: null
config_synchronizer:
  interval_secs: 900
  enabled: true
storage_node_cap: null
num_uncertified_blob_threshold: null
balance_check:
  interval_secs: 3600
  warning_threshold_mist: 5000000000
thread_pool:
  max_concurrent_tasks: null
  max_blocking_io_threads: 1024
