# See https://nexte.st/docs/configuration/ for configuration parameters.

[profile.default]
fail-fast = false # do not stop at first failure
slow-timeout = { period = "1m", terminate-after = 5 }

[[profile.default.overrides]]
filter = 'package(walrus-e2e-tests)'
threads-required = 4

[profile.ci]
retries = 2 # retry twice for a total of 3 attempts
slow-timeout = { period = "1m", terminate-after = 10 } # Timeout tests after 10 minutes

[[profile.ci.overrides]]
filter = 'package(walrus-e2e-tests) or package(walrus-sui) or test(nodes_drive_epoch_change)'
slow-timeout = { period = "2m", terminate-after = 5 } # Mark E2E tests as slow only after 2 minutes
threads-required = 4

[[profile.ci.overrides]]
filter = 'test(check_and_update_example_config) or test(check_and_update_openapi)'
retries = 0 # Do not retry these tests as they always succeed on the second run

[profile.simtest]
slow-timeout = { period = "5m", terminate-after = 6 } # Timeout tests after 30 minutes
test-threads = "num-cpus"

[profile.simtestnightly]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate"
# Show skipped tests in the CI output.
status-level = "fail"
# Do not cancel the test run on the first failure.
fail-fast = false
# Mark tests as slow after 30m, terminate after 1.5h
slow-timeout = { period = "30m", terminate-after = 3 }
